### ISSUE TITLE
Cannot get running

### ISSUE THREAD

**Issue by oleteacher** [EasyGithDev/PHPOpenAI-Playground#1]
Hello and thanks for sharing your repository.

I have cloned / installed with composer and can see the main page. Once I enter a term in prompt area and tap run, get this in dev error:

```
peError: Cannot read properties of undefined (reading 'forEach')
    at script.js:59:21
(anonymous) @ script.js:66
```

I have made a mod for the $apiKey since cannot use env on school server. It looks like this:

```
//$apiKey = getenv('OPENAI_API_KEY');
$apiKey = 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
```

Running PHP 8.1

Any ideas how to get running? The kids are sure to love this:)

**Comment by EasyGithDev** [comment]
Hello, 

I looked at the repository and realized that I forgot to version a folder. 
The application uses a temporary folder to store images generated by artificial intelligence.
I have fixed this error.

You can either add a folder named "download" to the root folder or update the application by performing a new clone.
Remember that the server must have write permissions in the "download" folder.

You can obviously add your key as you indicated in your message. Don't forget to do this manipulation in both files: imagine.php and variation.php.

I wish you a pleasant experience with the software. ;- )

**Comment by oleteacher** [comment]
Thanks for the reply @EasyGithDev 

Updated via git and still have the same error. Made sure download folder is writable.

The issue seems to be in this line `data.output.forEach((val) =`> { within this function:

```
function imagine(formData) {
    disableUi(true);

    postData("imagine.php", formData).then((data) => {
        // console.log(data); // JSON data parsed by `data.json()` call
        data.output.forEach((val) => {
            // console.log(val);
            let imgSrc = downloadDir + '/' + val;
            let thumbnail = createCard(imgSrc);
            $("#outputBox").append(thumbnail);
        });
    }).catch(error => {
        console.error(error);
    }).finally(() => {
        disableUi(false);
    });
}
```

**Comment by oleteacher** [comment]
Looking at closer, thinking it is the way I am using the $apiKey:

```
//$apiKey = getenv('OPENAI_API_KEY');
$apiKey = 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
```
Do you have any idea how to setup so env is stored local in directory? Ether in PHP or maybe even .env file.

**Comment by EasyGithDev** [comment]
Hello,

Hello,

Do you have à key from openai ?
Are you registered ?
The evening , i Will check with à direct string.

**Comment by oleteacher** [comment]
Yes, we have our api key.

We have a working chat platform for the kids to use, but your image playground is needed.

Thank you!

**Comment by EasyGithDev** [comment]
Hello, 

I made some modifications so that you can place your key in a configuration file. 
The file is located in the config folder, and all you have to do is change the function with your string. 

To access the Playground page, you need to enter the following URL: http://localhost/PHPOpenAI-Playground/public/. 
I haven't tested it with a virtual host, so some paths may not work if you're using a different URL. 

For future exchanges, it would be more useful if you directly send me the errors you see in the console on the network tab. This is where you can view the response from the imagine.php and variation.php files.

Regard's

**Comment by oleteacher** [comment]
Thank you for helping with more work:)

First a note:

Started fresh and did not use older code.

Doing `composer install` after git no longer installed the vendor folder for me. Had to copy vendor folder from previous git/composer install.

Now back to apikey issue. Got it working using the conf.php file!

To be clear for others that might have issue, we are not using localhost. Each classroom has their own tiny server running Ubuntu and Webmin. Teachers and students are restricted from making any type of global changes (ie; env or http.conf). Only sharing this as info. 

I thank you for taking the time to help us. Your image playground is great work.

Closing this issue.
