### ISSUE TITLE
Latest Release script.js Issue

### ISSUE THREAD

**Issue by oleteacher** [EasyGithDev/PHPOpenAI-Playground#2]
Greetings!

I setup the latest release. Getting error in the script.js.

Looking in dev console, see that script.js is calling display.php in root directory.

For example, I installed in example.com/playground and access example.com/playground/public

But js/script.js is calling display.php in example.com/display.php. Same for imagine.php.

For us, we cannot run on http://localhost:8000.

Is there something I can change to make example.com/playground/public work again?

Hope I am making sense:)

**Comment by oleteacher** [comment]
Got the path issue solved for us:

```
const getUrl = resource => {
    let url = new URL(window.location.href)
    return url.protocol + "//" + url.host + "/playground/public/" + resource;
}
```

But now have a JavaScript style alert that simply says "Serialize fail". No dev console error.

**Comment by EasyGithDev** [comment]
Hello, I will correct the JS error quickly. 
The second error comes from the unavailability of the Serialized folder.
The "serialized" folder must be writable, just like the "downloaded" folder.
The new version stores associated data for each image: the prompt, the painter, the dimensions, and the number of images.

**Comment by EasyGithDev** [comment]
Hello, I have corrected and modified the issues. It should work better now.

**Comment by oleteacher** [comment]
Very good, thank you.

What exactly does the serialized.php do? Looks like it retains data for the photos. Before putting this on the server I have to exaplain how all works or the school IT department will delete it.

**Comment by EasyGithDev** [comment]
Hello, 
serialization files allow you to store the information used to generate an image. 
For example:
`{"prompt":"a little girl eat an ice-cream","isize":"512x512","inumber":1,"rformat":"b64_json","painter":"paul-cezanne","filename":"img_644b9d0a66893_512x512.png"}
`This allows you to work iteratively on a prompt and not lose your work if you refresh your browser window.

**Comment by EasyGithDev** [comment]
Hello,

You can change the parameters like this :

```
<?php
return [
    'apiKey' => getenv('OPENAI_API_KEY'),
    'downloadDir' => __DIR__ . '/../download',
    'serializeDir' => __DIR__ . '/../serialize',
    'timeout' => 30
];

```
to :


```
<?php
return [
    'apiKey' => getenv('OPENAI_API_KEY'),
    'downloadDir' => __DIR__ . '/../download',
    'serializeDir' => __DIR__ . '/../download',
    'timeout' => 30
];

```
Then all files will be stored in the same directory.

**Comment by oleteacher** [comment]
Thank you @EasyGithDev, very good information.

All the files in the same directory is very good. Makes it simpler to clean up with cron job :)

Appreciate all your help and work on the playground, very nice setup and layout.
