### ISSUE TITLE
CURL Timeout

### ISSUE THREAD

**Issue by oleteacher** [EasyGithDev/PHPOpenAI-Playground#3]
Greetings!

I am trying to track down the timeout settings for CURL. I cannot seem to find a number value, or at least one I understand :)

At times the CURL seems to timeout fairly fast, like to up the timer.

In CurlRequest.php see this:

```
    protected int $connecttimeout = 0;

    protected int $timeout = 10;
```

Are these the setting I am looking for? 

Thank you!

**Comment by EasyGithDev** [comment]
Hello,

Sorry it s difficult to have acces to internet thoses Last week.
You can change the timeout value in the config file.
Regards

**Comment by oleteacher** [comment]
Thank you for reply.

I must be using an older version; the timeout is not in config file. Mine is like:

```
<?php
return [
    'apiKey' => getenv('OPENAI_API_KEY'),
    'downloadDir' => __DIR__ . '/../download',
    'serializeDir' => __DIR__ . '/../serialize'
];
```

Have made mods for classroom use and need to keep all my mods. Can I simply add the timeout to my config, or are there other files I must modify?

**Comment by EasyGithDev** [comment]
Hello,

Look the current code :

config/conf.php

Regards

**Comment by oleteacher** [comment]
Ok, as I stated we have modified your release before you added the option to config file. I simply asked:

"Have made mods for classroom use and need to keep all my mods. Can I simply add the timeout to my config, or are there other files I must modify?"

Anyway, thanks for your help.

**Comment by EasyGithDev** [comment]
Hello,

You can hardcode the value in the curling class or change the value in the ajax file.
https://github.com/EasyGithDev/PHPOpenAI-Playground/blob/main/public/imagine.php

Look at line 73.

In all case, it s better to add the value in the config file.

Regards

**Comment by oleteacher** [comment]
I forgot to thank you and close. Closing now:)
