### ISSUE TITLE
Set no $painter

### ISSUE THREAD

**Issue by 2braincells2go** [EasyGithDev/PHPOpenAI-Playground#4]
Set this up for use in a classroom and the kids love it. The teacher asked me about using with no painter value, just straight up dall-e-2.

Any input on how to use use as image generator without a painter? Maybe set no value for the $painter value?

Understand not the purpose you intended but it is so easy to use, teacher would like to continue.

Thanks for your time.

**Comment by EasyGithDev** [comment]
Hello,

After reading my code, i found this in the imagine file. 

$by = empty($painter) ? '' : " by $painter";
$prompt .= $by;

So, it's possible to not send the painter or an empty painter.
You can try to add in the index.html file a new empty painter.

ON line 88 you can add : 

 <optgroup label="Default">
 <option value="">Default</option> 
</optgroup>

Let's me know what's append after those changes.

Regard's

**Comment by oleteacher** [comment]
Thank you for reply. (fellow teacher here - not 2braincells2go)

I saw the $by code and did some experimenting before asking. I think my lack of quality prompts caused bad results.

I have added an option to the dropdown for default. Will let the teacher experiment with an empty value and then maybe send a value of default.

Thank you again for your help.

**Comment by 2braincells2go** [comment]
Will close this, thank you for your help @EasyGithDev
