### ISSUE TITLE
Using Dalle 3

### ISSUE THREAD

**Issue by oleteacher** [EasyGithDev/PHPOpenAI-Playground#5]
I have attempted to discover where/how to make the system use dalle 3. Failed miserably. My coding helper is out on exteneded sick leave so all of this is placed upon me.

We are using this in the classroom and dalle 2 does not generate people very well. Lots of missing body parts, weird faces, etc.

Could you give me some advice on setting up to use dalle 3 and maybe increasing the allowed image size? Would be greatly appreciated.

Thank you for your time.

**Comment by EasyGithDev** [comment]
Hello,

I don't know how dall-e 3 is working. I imagine I need to update the library that manages the connection. I'll start by reading the documentation.
In dall-2 you can not increase the image size. the maximum size that the service returns is already implemented.

**Comment by oleteacher** [comment]
Thank you for considering.

What I meant is dall-e 3 has different sizes than dall-e 2.

"According to the system prompt, DALL-E 3 currently generates images in the resolutions "1792x1024", "1024x1024", and "1024x1792"."

I attempted to change the model url, but all tries were failures. I honestly thought would be simple change for me to make. Seems the URL is even correct based on this curl from openai:

```
curl https://api.openai.com/v1/images/generations \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "dall-e-3",
    "prompt": "a white siamese cat",
    "n": 1,
    "size": "1024x1024"
  }'
```

Little above my head though:)

**Comment by EasyGithDev** [comment]
Hello,

Change are possibles, but there are many limitations.
First, only create method support dall-e-3.
Not variations, not edition, etc ... are available.
Second, dall-e-3 only 5 images per minute.

It's not my choice, this is the openai limitations for using API.

regard's

**Comment by oleteacher** [comment]
Ok, thanks for looking into.

**Comment by EasyGithDev** [comment]
Hello,

I have make the changes.
You can use dall-e-3.
You need to update the PHPopenAI library via composer.
Maybe you will to work on the user interface.

In the file config change the number 2 by 3 :

return [
    'apiKey' => getenv('OPENAI_API_KEY'),
    'downloadDir' => __DIR__ . '/../download',
    'serializeDir' => __DIR__ . '/../serialize',
    'dalleVersion' => 2,
    'timeout' => 30
];

Personally, I think that you should continue to use dall-e-2 while waiting for dall-e-3 to offer the same characteristics as the version 2.

regard's

**Comment by oleteacher** [comment]
Thank you, I am very grateful for your work!

"Personally, I think that you should continue to use dall-e-2 while waiting for dall-e-3 to offer the same characteristics as the version 2."

Yes, I understand but when kids bug / bother you enough, you give in :) 

Dall-e 3 is progressing very well and creates such better images, hard to ignore. For instance, prompt "peter rabbit riding a motorcycle":

**Dall-e 2**
![1708890014700_dall-e2](https://github.com/EasyGithDev/PHPOpenAI-Playground/assets/26278259/fd32ebc6-9ce7-4971-97aa-80d1abe86a45)

**Dall-e 3**
![1708890014700_dall-e3](https://github.com/EasyGithDev/PHPOpenAI-Playground/assets/26278259/dbc87fb7-1922-450a-b4ce-6009b262256e)

Thank you again!
